// <auto-generated />
using System;
using Atilim.Services.Identity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atilim.Services.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityContext))]
    partial class IdentityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.ContactInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobilePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentIdentityId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("StudentIdentityId")
                        .IsUnique();

                    b.ToTable("ContactInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "DEMİRCİKARA MAH. B.ONAT CAD. HEDE SİT. B BLOK NO : 1",
                            City = "ANKARA",
                            Country = "Türkiye",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 321, DateTimeKind.Local).AddTicks(181),
                            District = "PURSAKLAR",
                            Email = "mno@xyz.com",
                            IsDeleted = false,
                            MobilePhoneNumber = "5555424245",
                            StudentIdentityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "CUMHURİYET MAH. BİRİNCİ SOK. İKİNCİ APT. NO:111/6",
                            City = "Ankara",
                            Country = "Türkiye",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 321, DateTimeKind.Local).AddTicks(203),
                            District = "YENİMAHALLE",
                            Email = "abc@hotmail.com",
                            IsDeleted = false,
                            MobilePhoneNumber = "5332342342",
                            StudentIdentityId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "SİTELER MAHALLESİ 6223 SOKAK DURU APT. NO:11 KAT:3 ",
                            City = "Ankara",
                            Country = "Türkiye",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 321, DateTimeKind.Local).AddTicks(205),
                            District = "POLATLI",
                            Email = "klm@outlook.com",
                            IsDeleted = false,
                            MobilePhoneNumber = "5408932042",
                            StudentIdentityId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "TURAN GÜNEŞ BULVARI TAMTAM SİTESİ 13. CAD. NO:51",
                            City = "Ankara",
                            Country = "Türkiye",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 321, DateTimeKind.Local).AddTicks(208),
                            District = "KEÇİÖREN",
                            Email = "ghi@abc.com",
                            IsDeleted = false,
                            MobilePhoneNumber = "5305464646",
                            StudentIdentityId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "AHMET HAMDİ SOK. NO:19/15",
                            City = "Ankara",
                            Country = "Türkiye",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 321, DateTimeKind.Local).AddTicks(209),
                            District = "SİNCAN",
                            Email = "prs@hotmail.com",
                            IsDeleted = false,
                            MobilePhoneNumber = "5302908432",
                            StudentIdentityId = 5
                        },
                        new
                        {
                            Id = 6,
                            Address = "KUŞADASI SOK. NO:123 KARAAĞAÇ",
                            City = "Ankara",
                            Country = "Türkiye",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 321, DateTimeKind.Local).AddTicks(211),
                            District = "ÇANKAYA",
                            Email = "def@gmail.com",
                            IsDeleted = false,
                            MobilePhoneNumber = "5437657567",
                            StudentIdentityId = 6
                        });
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurriculumName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumName")
                        .IsUnique()
                        .HasDatabaseName("CurriculumName");

                    b.HasIndex("Id");

                    b.ToTable("Curriculums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7044),
                            CurriculumName = "Bilgisayar_Mühendisliği",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7047),
                            CurriculumName = "Grafik_Mühendisliği",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7049),
                            CurriculumName = "Ingiliz_Dil_Edebiyatı",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.CurriculumLesson", b =>
                {
                    b.Property<int>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("CurriculumId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("CurriculumLesson");

                    b.HasData(
                        new
                        {
                            CurriculumId = 3,
                            LessonId = 1
                        },
                        new
                        {
                            CurriculumId = 3,
                            LessonId = 2
                        },
                        new
                        {
                            CurriculumId = 1,
                            LessonId = 3
                        },
                        new
                        {
                            CurriculumId = 3,
                            LessonId = 4
                        },
                        new
                        {
                            CurriculumId = 3,
                            LessonId = 5
                        },
                        new
                        {
                            CurriculumId = 2,
                            LessonId = 6
                        },
                        new
                        {
                            CurriculumId = 2,
                            LessonId = 1
                        },
                        new
                        {
                            CurriculumId = 1,
                            LessonId = 7
                        },
                        new
                        {
                            CurriculumId = 1,
                            LessonId = 1
                        });
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LessonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LessonCode")
                        .IsUnique();

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(6993),
                            Credit = 5,
                            IsDeleted = false,
                            LessonCode = "HUM101",
                            LessonName = "Türk Demokrasi Tarihi",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7003),
                            Credit = 6,
                            IsDeleted = false,
                            LessonCode = "MATH102",
                            LessonName = "Calculus 2",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7005),
                            Credit = 6,
                            IsDeleted = false,
                            LessonCode = "MATE103",
                            LessonName = "Metalurjiye Giriş",
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7006),
                            Credit = 5,
                            IsDeleted = false,
                            LessonCode = "GRA105",
                            LessonName = "Grafik Dizayn",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7008),
                            Credit = 4,
                            IsDeleted = false,
                            LessonCode = "CMPE201",
                            LessonName = "Bilgisayar Teknolojileri",
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7010),
                            Credit = 4,
                            IsDeleted = false,
                            LessonCode = "ENG102",
                            LessonName = "İngilizce 2",
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(7011),
                            Credit = 6,
                            IsDeleted = false,
                            LessonCode = "MATH201",
                            LessonName = "İleri Calculus ",
                            Status = true
                        });
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StudentIdentityId")
                        .HasColumnType("int");

                    b.Property<int>("StudentNo")
                        .HasMaxLength(25)
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("Id");

                    b.HasIndex("StudentIdentityId")
                        .IsUnique();

                    b.HasIndex("StudentNo")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 323, DateTimeKind.Local).AddTicks(1257),
                            CurriculumId = 1,
                            IsDeleted = false,
                            StudentIdentityId = 1,
                            StudentNo = 23462368
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 323, DateTimeKind.Local).AddTicks(1264),
                            CurriculumId = 1,
                            IsDeleted = false,
                            StudentIdentityId = 2,
                            StudentNo = 27482379
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 323, DateTimeKind.Local).AddTicks(1266),
                            CurriculumId = 2,
                            IsDeleted = false,
                            StudentIdentityId = 3,
                            StudentNo = 34565479
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 323, DateTimeKind.Local).AddTicks(1267),
                            CurriculumId = 2,
                            IsDeleted = false,
                            StudentIdentityId = 4,
                            StudentNo = 53456346
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 323, DateTimeKind.Local).AddTicks(1269),
                            CurriculumId = 3,
                            IsDeleted = false,
                            StudentIdentityId = 5,
                            StudentNo = 34674575
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 323, DateTimeKind.Local).AddTicks(1271),
                            CurriculumId = 3,
                            IsDeleted = false,
                            StudentIdentityId = 6,
                            StudentNo = 64672359
                        });
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.StudentIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactInformationId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TCIdentificationNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("TCIdentificationNo")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "Surname");

                    b.ToTable("StudentIdentities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityOfBirth = "Kayseri",
                            ContactInformationId = 0,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(2598),
                            DateOfBirth = new DateTime(1983, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Hasan",
                            StudentId = 1,
                            Surname = "Ersoy",
                            TCIdentificationNo = "45456747611",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CityOfBirth = "Adana",
                            ContactInformationId = 0,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(2681),
                            DateOfBirth = new DateTime(2000, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Mehmet",
                            StudentId = 2,
                            Surname = "Yılmaz",
                            TCIdentificationNo = "67967856634",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CityOfBirth = "Ankara",
                            ContactInformationId = 0,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(2690),
                            DateOfBirth = new DateTime(2001, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Ahmet",
                            StudentId = 3,
                            Surname = "Ünal",
                            TCIdentificationNo = "72347322958",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CityOfBirth = "Sivas",
                            ContactInformationId = 0,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(2695),
                            DateOfBirth = new DateTime(2000, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Mustafa",
                            StudentId = 4,
                            Surname = "Işık",
                            TCIdentificationNo = "97850348520",
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CityOfBirth = "Uşak",
                            ContactInformationId = 0,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(2701),
                            DateOfBirth = new DateTime(2001, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Ayşe",
                            StudentId = 5,
                            Surname = "Erdoğan",
                            TCIdentificationNo = "32756874239",
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            CityOfBirth = "Kütahya",
                            ContactInformationId = 0,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2023, 9, 17, 17, 35, 48, 325, DateTimeKind.Local).AddTicks(2706),
                            DateOfBirth = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Fatma",
                            StudentId = 6,
                            Surname = "Korkmaz",
                            TCIdentificationNo = "98423479320",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d77ab0e-0e9f-42f8-b84c-a7bb0391631d",
                            Email = "admin@atilimProject.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "atilim",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "733ef870-dd8f-4408-a070-fed38ee23ffd",
                            Surname = "admin",
                            TwoFactorEnabled = false,
                            UserName = "atilim.admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "127fdbae-7c81-4c50-9f20-23e1e0bb5d95",
                            Email = "hasan.ersoy@atilimProject.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "hasan",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eee8cfbd-09a1-4a0f-a181-868edfe26f99",
                            Surname = "ersoy",
                            TwoFactorEnabled = false,
                            UserName = "hasan.ersoy"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9e301ae6-fe74-4c41-a750-f43eb0f83d73",
                            Email = "mehmet.yilmaz@atilimProject.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "mehmet",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7189670-7e5b-431e-9bbb-f33da4548482",
                            Surname = "yilmaz",
                            TwoFactorEnabled = false,
                            UserName = "mehmet.yilmaz"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a6919cea-0c37-47fe-94c0-76f52eee8e7e",
                            Email = "ahmet.unal@atilimProject.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "ahmet",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64ed9d98-cc95-49de-9a5c-b6ee37249193",
                            Surname = "unal",
                            TwoFactorEnabled = false,
                            UserName = "ahmet.unal"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b971ac0a-7732-487a-bba9-75566ddc5bf6",
                            Email = "mustafa.isik@atilimProject.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "mustafa",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "125219e1-59a9-4226-9ac2-0af78b91a53e",
                            Surname = "isik",
                            TwoFactorEnabled = false,
                            UserName = "mustafa.isik"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c929b846-8aa1-43f2-a1a3-3d9464290cb0",
                            Email = "ayse.erdogan@atilimProject.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "ayse",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ac4d01a-a4e0-4880-a397-2fde5d5311df",
                            Surname = "erdogan",
                            TwoFactorEnabled = false,
                            UserName = "ayse.erdogan"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d757067c-f0b8-4e80-9d6b-2fceff98b667",
                            Email = "fatma.korkmaz@atilimProject.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "fatma",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d111a67c-1b92-4aa4-9c6c-3fee3f24058b",
                            Surname = "korkmaz",
                            TwoFactorEnabled = false,
                            UserName = "fatma.korkmaz"
                        });
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "b2ebc2a6-9761-43a1-9941-9f59b87b613f",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "1047007a-604a-4010-bd99-b06b5bfaf78a",
                            Name = "student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.ContactInformation", b =>
                {
                    b.HasOne("Atilim.Services.Identity.Domain.Entities.StudentEntities.StudentIdentity", "StudentIdentity")
                        .WithOne("ContactInformation")
                        .HasForeignKey("Atilim.Services.Identity.Domain.Entities.StudentEntities.ContactInformation", "StudentIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentIdentity");
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.CurriculumLesson", b =>
                {
                    b.HasOne("Atilim.Services.Identity.Domain.Entities.StudentEntities.Curriculum", "Curriculum")
                        .WithMany("CurriculumLessons")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atilim.Services.Identity.Domain.Entities.StudentEntities.Lesson", "Lesson")
                        .WithMany("CurriculumLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.Student", b =>
                {
                    b.HasOne("Atilim.Services.Identity.Domain.Entities.StudentEntities.Curriculum", "Curriculum")
                        .WithMany("Students")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atilim.Services.Identity.Domain.Entities.StudentEntities.StudentIdentity", "StudentIdentity")
                        .WithOne("Student")
                        .HasForeignKey("Atilim.Services.Identity.Domain.Entities.StudentEntities.Student", "StudentIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("StudentIdentity");
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.StudentIdentity", b =>
                {
                    b.HasOne("Atilim.Services.Identity.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Atilim.Services.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Atilim.Services.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atilim.Services.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Atilim.Services.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.Curriculum", b =>
                {
                    b.Navigation("CurriculumLessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.Lesson", b =>
                {
                    b.Navigation("CurriculumLessons");
                });

            modelBuilder.Entity("Atilim.Services.Identity.Domain.Entities.StudentEntities.StudentIdentity", b =>
                {
                    b.Navigation("ContactInformation");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
